# server
server:
 port: 8888
 
# DB
spring:
 datasource:
  url: jdbc:oracle:thin:@211.105.15.179:1521:xe
  username: PAPERHOUSE
  password: PAPERHOUSE
  driver-class-name : oracle.jdbc.OracleDriver
  
# resource setting
 mvc:
  static-path-pattern: static/**
 resources:
  static-locations:  - classpath:/static/
  add-mappings: true

 
 mail: 
  host: smtp.gmail.com
  port: 587
  username: superpower1226@gmail.com
  password: FKFFKGH@12
  properties: 
   mail: 
    smtp: 
     auth: true
     starttls: 
      enable: true    