# server
server:
 port: 8888 
 servlet:   session:     timeout: 7200


# DB
spring:
 datasource:
  url: jdbc:oracle:thin:@211.105.15.179:1521:xe
  username: PAPERHOUSE
  password: PAPERHOUSE
  driver-class-name : oracle.jdbc.OracleDriver
 devtools:
  livereload:
   enabled: true
 freemarker:
  cache: false 
# resource setting
 mvc:
  static-path-pattern: static/**
 resources:
  static-locations:  - classpath:/static/
  add-mappings: true

 servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/bit-final-project/paperHouse/src/main/resources/static/upload
      max-file-size: 100MB
      max-request-size: 100MB
   
 
 mail: 
  host: smtp.gmail.com
  port: 587
  username: bitcamp5j0@gmail.com
  password: dhwhdlqslek
  properties: 
   mail: 
    smtp: 
     auth: true
     starttls: 
      enable: true
 security:    oauth2:      client:        registration:
         google:
           client-id: 280904523337-i5roff0vdqf6g3q8v4taga309spbva4a.apps.googleusercontent.com
           client-secret: gIvrrh7639tx47CkyiMKV1_o
           scope:            - email
            - profile
         
         facebook:
           client-id: 3244109895637895
           client-secret: cd7e8c11a81498d40412d19262f23094
           scope:
            - email
            - public_profile
             
         naver:
           client-id: p_GH5l7QShUuX8wXwqX0
           client-secret: L02Yt0AKPj
           scope:
            - email
            - name
           client-name: Naver
           authorization-grant-type: authorization_code
           redirect-uri: http://localhost:8888/login/oauth2/code/naver  
           
         kakao:
           client-id: 91ffeb1e5f42b18b0c79ba03012248d9
           client-secret: 8pDxZTgBNOPQ5MbJLRqnbsZBggAt49ez
           scope:
            - account_email
           client-name: kakao
           client-authentication-method: POST
           authorization-grant-type: authorization_code
           redirect-uri: http://localhost:8888/login/oauth2/code/kakao  
                      
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.   
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account      